version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8881:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress

  wordpress:
    depends_on:
     - db
    image: wordpress:latest
    ports:
      - "8880:80"
    restart: always
    tty: true
    stdin_open: true
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wordpress:/var/www/html/
      - ./src/wp-content/themes/tuleva:/var/www/html/wp-content/themes/tuleva

volumes:
  db_data: {}
