version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: d56838_tuleva20
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5.1
    restart: always
    ports:
      - 8881:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
      UPLOAD_LIMIT: 300M
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 300
    volumes:
        - ./php.ini:/usr/local/etc/php/php.ini
  wordpress:
    depends_on:
     - db
    image: wordpress:latest
    ports:
      - "8880:80"
    restart: always
    tty: true
    stdin_open: true
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: d56838_tuleva20
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: true
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wordpress:/var/www/html/
      - ./src/wp-content/themes/tuleva:/var/www/html/wp-content/themes/tuleva

volumes:
  db_data: {}
