<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
    'key' => 'group_5914d42c0c3f8',
    'title' => 'Contact page heading',
    'fields' => array (
        array (
            'key' => 'field_5914d4bd1647a',
            'label' => 'Heading',
            'name' => 'heading',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5914d4df1647b',
            'label' => 'Subheading',
            'name' => 'subheading',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_template',
                'operator' => '==',
                'value' => 'page_contact.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'format',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
));

// acf_add_local_field_group(array(
// 	'key' => 'group_5a0aeaa387e48',
// 	'title' => 'Contacts',
// 	'fields' => array(
// 		array(
// 			'key' => 'field_5a0b01fbdf9ba',
// 			'label' => 'Contacts block',
// 			'name' => 'contacts_block',
// 			'type' => 'repeater',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'collapsed' => '',
// 			'min' => 0,
// 			'max' => 0,
// 			'layout' => 'row',
// 			'button_label' => 'Add block',
// 			'sub_fields' => array(
// 				array(
// 					'key' => 'field_5a0b02f7df9bc',
// 					'label' => 'Block title',
// 					'name' => 'block_title',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 1,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 				),
// 				array(
// 					'key' => 'field_5a0b023edf9bb',
// 					'label' => 'Contacts',
// 					'name' => 'contacts',
// 					'type' => 'repeater',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'collapsed' => '',
// 					'min' => 0,
// 					'max' => 0,
// 					'layout' => 'row',
// 					'button_label' => 'Add Contact',
// 					'sub_fields' => array(
// 						array(
// 							'key' => 'field_5a0b0358df9bd',
// 							'label' => 'Name',
// 							'name' => 'name',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 1,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 						),
// 						array(
// 							'key' => 'field_5a0b0364df9be',
// 							'label' => 'Role',
// 							'name' => 'role',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 						),
// 						array(
// 							'key' => 'field_5a0b038edf9c0',
// 							'label' => 'Email',
// 							'name' => 'email',
// 							'type' => 'email',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 						),
// 						array(
// 							'key' => 'field_5a0b0376df9bf',
// 							'label' => 'Phone',
// 							'name' => 'phone',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 						),
// 						array(
// 							'key' => 'field_5a0b03f5c1f4e',
// 							'label' => 'Image',
// 							'name' => 'image',
// 							'type' => 'image',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array(
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'return_format' => 'url',
// 							'preview_size' => 'thumbnail',
// 							'library' => 'all',
// 							'min_width' => 160,
// 							'min_height' => 160,
// 							'min_size' => '',
// 							'max_width' => '',
// 							'max_height' => '',
// 							'max_size' => '',
// 							'mime_types' => '',
// 						),
// 					),
// 				),
// 			),
// 		),
// 	),
// 	'location' => array(
// 		array(
// 			array(
// 				'param' => 'page_template',
// 				'operator' => '==',
// 				'value' => 'page_contact.php',
// 			),
// 		),
// 	),
// 	'menu_order' => 3,
// 	'position' => 'normal',
// 	'style' => 'seamless',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => array(
// 		0 => 'the_content',
// 		1 => 'excerpt',
// 		2 => 'custom_fields',
// 		3 => 'discussion',
// 		4 => 'comments',
// 		5 => 'revisions',
// 		6 => 'format',
// 		7 => 'featured_image',
// 		8 => 'categories',
// 		9 => 'tags',
// 		10 => 'send-trackbacks',
// 	),
// 	'active' => 1,
// 	'description' => '',
// ));

acf_add_local_field_group( array(
	'key' => 'group_656cdc301067b',
	'title' => 'Contacts',
	'fields' => array(
		array(
			'key' => 'field_656cdc30109ab',
			'label' => 'Contacts',
			'name' => 'contacts_block',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Block',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_656cdc30d012c',
					'label' => 'Block title',
					'name' => 'block_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'wpml_cf_preferences' => 2,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_656cdc30109ab',
				),
				array(
					'key' => 'field_656cdc30d0134',
					'label' => 'Contact categories',
					'name' => 'contact_categories',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'wpml_cf_preferences' => 1,
					'layout' => 'block',
					'min' => 0,
					'max' => 2,
					'collapsed' => '',
					'button_label' => 'Add Category',
					'rows_per_page' => 20,
					'parent_repeater' => 'field_656cdc30109ab',
					'sub_fields' => array(
						array(
							'key' => 'field_656cdc327c9fd',
							'label' => 'Category title',
							'name' => 'category_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_656cdc30d0134',
						),
						array(
							'key' => 'field_656cdc327ca05',
							'label' => 'Contacts',
							'name' => 'contacts',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 1,
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Contact',
							'rows_per_page' => 20,
							'parent_repeater' => 'field_656cdc30d0134',
							'sub_fields' => array(
								array(
									'key' => 'field_656cdc34277d6',
									'label' => 'Name',
									'name' => 'name',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_656cdc327ca05',
								),
								array(
									'key' => 'field_656cdc34277df',
									'label' => 'Role',
									'name' => 'role',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_656cdc327ca05',
								),
								array(
									'key' => 'field_656cdc34277e6',
									'label' => 'Email',
									'name' => 'email',
									'aria-label' => '',
									'type' => 'email',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 1,
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_656cdc327ca05',
								),
								array(
									'key' => 'field_656cdc34277ee',
									'label' => 'Phone',
									'name' => 'phone',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_656cdc327ca05',
								),
								array(
									'key' => 'field_656cdc34277f6',
									'label' => 'Image',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 1,
									'return_format' => 'url',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_656cdc327ca05',
								),
							),
						),
					),
				),
				array(
					'key' => 'field_656ce3027bd36',
					'label' => 'Background color',
					'name' => 'background_color',
					'aria-label' => '',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'wpml_cf_preferences' => 1,
					'choices' => array(
						'None' => 'None',
						'Blue' => 'Blue',
					),
					'default_value' => 'None',
					'return_format' => 'value',
					'allow_null' => 0,
					'other_choice' => 0,
					'layout' => 'vertical',
					'save_other_choice' => 0,
					'parent_repeater' => 'field_656cdc30109ab',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'page_contact.php',
			),
		),
	),
	'menu_order' => 3,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'custom_fields',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'format',
		7 => 'featured_image',
		8 => 'categories',
		9 => 'tags',
		10 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
) );

endif;
