<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
    'key' => 'group_5903bab1e4867',
    'title' => 'Front components',
    'fields' => array (
        array (
            'key' => 'field_5903baeb36a07',
            'label' => 'Components',
            'name' => 'front_components',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'button_label' => 'Add Comonent',
            'min' => '',
            'max' => '',
            'layouts' => array (
                array (
                    'key' => '5903baf131f99',
                    'name' => 'text_boxes',
                    'label' => 'Text boxes',
                    'display' => 'row',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5903c0a233099',
                            'label' => 'Box 1',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array (
                            'key' => 'field_5903c0c03309b',
                            'label' => 'Title 1',
                            'name' => 'title_1',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903c221ddbb0',
                            'label' => 'Title 1 border',
                            'name' => 'title_1_border',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array (
                                'none' => 'None',
                                'lightblue' => 'Light blue',
                                'blue' => 'Blue',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 'none',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                        array (
                            'key' => 'field_5903c1c712a93',
                            'label' => 'Text 1',
                            'name' => 'text_1',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 0,
                            'delay' => 0,
                        ),
                        array (
                            'key' => 'field_5903c0b43309a',
                            'label' => 'Box 2',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array (
                            'key' => 'field_5903c0e23309c',
                            'label' => 'Title 2',
                            'name' => 'title_2',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903c27bddbb1',
                            'label' => 'Title 2 border',
                            'name' => 'title_2_border',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array (
                                'none' => 'None',
                                'lightblue' => 'Light blue',
                                'blue' => 'Blue',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 'none',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                        array (
                            'key' => 'field_5903c0ec3309d',
                            'label' => 'Text 2',
                            'name' => 'text_2',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 0,
                            'delay' => 0,
                        ),
                        array (
                            'key' => 'field_5903d10e03694',
                            'label' => 'Settings',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array (
                            'key' => 'field_5905e1aa8ce0d',
                            'label' => 'Component ID',
                            'name' => 'component_id',
                            'type' => 'text',
                            'instructions' => 'Single word, no spaces. Underscores and dashes allowed',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'text-boxes-component',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903d0dd03693',
                            'label' => 'Box border radius',
                            'name' => 'box_border_radius',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array (
                                4 => '4px',
                                8 => '8px',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 4,
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                        array (
                            'key' => 'field_5903d5920c5ba',
                            'label' => 'Component spacing',
                            'name' => 'spacing',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array (
                                'full' => 'Wide',
                                'half' => 'Narrow',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 'half',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '5903ca21147fb',
                    'name' => 'button',
                    'label' => 'Button',
                    'display' => 'row',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5903ca2a147fc',
                            'label' => 'Text',
                            'name' => 'text',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903ca45147fd',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5905e1908ce0c',
                            'label' => 'Component ID',
                            'name' => 'component_id',
                            'type' => 'text',
                            'instructions' => 'Single word, no spaces. Underscores and dashes allowed',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'button-component',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903d89cfc7d6',
                            'label' => 'Component spacing',
                            'name' => 'spacing',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array (
                                'full' => 'Wide',
                                'half' => 'Narrow',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 'half',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '5903cb867a89e',
                    'name' => 'text_block',
                    'label' => 'Text block',
                    'display' => 'row',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5903cb8d7a89f',
                            'label' => 'Text',
                            'name' => 'text',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => '',
                        ),
                        array (
                            'key' => 'field_5905e17a8ce0b',
                            'label' => 'Component ID',
                            'name' => 'component_id',
                            'type' => 'text',
                            'instructions' => 'Single word, no spaces. Underscores and dashes allowed',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'text-block-component',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903d8fafc7d8',
                            'label' => 'Component spacing',
                            'name' => 'spacing',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array (
                                'full' => 'Wide',
                                'half' => 'Narrow',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 'half',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '5903d6df02ba5',
                    'name' => 'statistics_block',
                    'label' => 'Statistics block',
                    'display' => 'table',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5903d6fa02ba6',
                            'label' => 'Members',
                            'name' => 'members',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                        ),
                        array (
                            'key' => 'field_5903d70e02ba7',
                            'label' => 'Stock market volume (€)',
                            'name' => 'stock_market_volume',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                        ),
                        array (
                            'key' => 'field_5903d73602ba8',
                            'label' => 'Bonds volume (€)',
                            'name' => 'bonds_volume',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                        ),
                        array (
                            'key' => 'field_5905e15b8ce0a',
                            'label' => 'Component ID',
                            'name' => 'component_id',
                            'type' => 'text',
                            'instructions' => 'Single word, no spaces. Underscores and dashes allowed',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'statistics-block-component',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903d74b02ba9',
                            'label' => 'Has background color',
                            'name' => 'has_background_color',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        array (
                            'key' => 'field_5903d76a02baa',
                            'label' => 'Has padding',
                            'name' => 'has_padding',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        array (
                            'key' => 'field_5903d8bffc7d7',
                            'label' => 'Component spacing',
                            'name' => 'spacing',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array (
                                'full' => 'Wide',
                                'half' => 'Narrow',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 'half',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '5903df8d540f3',
                    'name' => 'quotes_block',
                    'label' => 'Quotes block',
                    'display' => 'row',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5903dfd7540f4',
                            'label' => 'Quote 1',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array (
                            'key' => 'field_5903e103540f8',
                            'label' => 'Quote 1 text',
                            'name' => 'quote_1_text',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => '',
                        ),
                        array (
                            'key' => 'field_5903e18d540fd',
                            'label' => 'Quote 1 author',
                            'name' => 'quote_1_author',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903e1cf54100',
                            'label' => 'Quote 1 author URL',
                            'name' => 'quote_1_author_url',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903e30f766d2',
                            'label' => 'Quote 1 author image',
                            'name' => 'quote_1_author_image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => 40,
                            'min_height' => 40,
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => 1,
                            'mime_types' => '',
                        ),
                        array (
                            'key' => 'field_5903e0de540f5',
                            'label' => 'Quote 2',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array (
                            'key' => 'field_5903e12f540f9',
                            'label' => 'Quote 2 text',
                            'name' => 'quote_2_text',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => '',
                        ),
                        array (
                            'key' => 'field_5903e1a8540fe',
                            'label' => 'Quote 2 author',
                            'name' => 'quote_2_author',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903e1f954101',
                            'label' => 'Quote 2 author URL',
                            'name' => 'quote_2_author_url',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903e376766d3',
                            'label' => 'Quote 2 author image',
                            'name' => 'quote_2_author_image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => 40,
                            'min_height' => 40,
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => 1,
                            'mime_types' => '',
                        ),
                        array (
                            'key' => 'field_5903e0e9540f6',
                            'label' => 'Quote 3',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array (
                            'key' => 'field_5903e146540fa',
                            'label' => 'Quote 3 text',
                            'name' => 'quote_3_text',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => '',
                        ),
                        array (
                            'key' => 'field_5903e1ba540ff',
                            'label' => 'Quote 3 author',
                            'name' => 'quote_3_author',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903e20754102',
                            'label' => 'Quote 3 author URL',
                            'name' => 'quote_3_author_url',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903e387766d4',
                            'label' => 'Quote 3 author image',
                            'name' => 'quote_3_author_image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => 40,
                            'min_height' => 40,
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => 1,
                            'mime_types' => '',
                        ),
                        array (
                            'key' => 'field_5903e0f4540f7',
                            'label' => 'Settings',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array (
                            'key' => 'field_5905e1168ce09',
                            'label' => 'Component ID',
                            'name' => 'component_id',
                            'type' => 'text',
                            'instructions' => 'Single word, no spaces. Underscores and dashes allowed',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'quotes-block-component',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903e425060c0',
                            'label' => 'Has background color',
                            'name' => 'has_background_color',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 1,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        array (
                            'key' => 'field_5903e4aa060c1',
                            'label' => 'Has padding',
                            'name' => 'has_padding',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 1,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        array (
                            'key' => 'field_5903e170540fc',
                            'label' => 'Component spacing',
                            'name' => 'spacing',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array (
                                'full' => 'Wide',
                                'half' => 'Narrow',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 'half',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '5903ea1bc9793',
                    'name' => 'hero_block',
                    'label' => 'Hero block',
                    'display' => 'row',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5903ea24c9794',
                            'label' => 'Heading',
                            'name' => 'heading',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903ea33c9795',
                            'label' => 'Text',
                            'name' => 'text',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                            'delay' => 0,
                        ),
                        array (
                            'key' => 'field_5905e0cf8ce07',
                            'label' => 'Component ID',
                            'name' => 'component_id',
                            'type' => 'text',
                            'instructions' => 'Single word, no spaces. Underscores and dashes allowed',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'hero-block-component',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903ec931b749',
                            'label' => 'Component spacing',
                            'name' => 'spacing',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array (
                                'full' => 'Wide',
                                'half' => 'Narrow',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 'half',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '5903efa3dcce4',
                    'name' => 'people_slider',
                    'label' => 'People slider',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5903efbedcce5',
                            'label' => 'Persons',
                            'name' => 'persons',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => 'field_5903f02bdcce6',
                            'min' => 1,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => 'Add person',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_5903f02bdcce6',
                                    'label' => 'Name',
                                    'name' => 'name',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array (
                                    'key' => 'field_5903f04cdcce7',
                                    'label' => 'Description',
                                    'name' => 'description',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => 4,
                                    'new_lines' => '',
                                ),
                                array (
                                    'key' => 'field_5903f068dcce8',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'all',
                                    'min_width' => 96,
                                    'min_height' => 96,
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => 1,
                                    'mime_types' => '',
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_5905e1068ce08',
                            'label' => 'Component ID',
                            'name' => 'component_id',
                            'type' => 'text',
                            'instructions' => 'Single word, no spaces. Underscores and dashes allowed',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'people-slider-component',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_5903ffa17b0b7',
                            'label' => 'Component spacing',
                            'name' => 'spacing',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array (
                                'full' => 'Wide',
                                'half' => 'Narrow',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 'half',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '590402d19b3f5',
                    'name' => 'tabs',
                    'label' => 'Tabs',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5904031d9b3fc',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_590402de9b3fb',
                            'label' => 'Tabs',
                            'name' => 'tabs',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => 'field_590403329b3fd',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'row',
                            'button_label' => '',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_590403329b3fd',
                                    'label' => 'Name',
                                    'name' => 'name',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array (
                                    'key' => 'field_590403889b400',
                                    'label' => 'Content layout',
                                    'name' => 'columns',
                                    'type' => 'radio',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array (
                                        1 => 'One column',
                                        2 => 'Two columns',
                                    ),
                                    'allow_null' => 0,
                                    'other_choice' => 0,
                                    'save_other_choice' => 0,
                                    'default_value' => 1,
                                    'layout' => 'horizontal',
                                    'return_format' => 'value',
                                ),
                                array (
                                    'key' => 'field_5904033d9b3fe',
                                    'label' => 'Content',
                                    'name' => 'content',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array (
                                    'key' => 'field_590403709b3ff',
                                    'label' => 'Content 2',
                                    'name' => 'content_2',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'field_590403889b400',
                                                'operator' => '==',
                                                'value' => '2',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_5905e08f8ce06',
                            'label' => 'Component ID',
                            'name' => 'component_id',
                            'type' => 'text',
                            'instructions' => 'Single word, no spaces. Underscores and dashes allowed',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'tabs-component',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_590402d19b3fa',
                            'label' => 'Component spacing',
                            'name' => 'spacing',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array (
                                'full' => 'Wide',
                                'half' => 'Narrow',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 'half',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page_front.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'format',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_5903b93919ba6',
    'title' => 'Front heading',
    'fields' => array (
        array (
            'key' => 'field_5903b9392e950',
            'label' => 'Heading',
            'name' => 'heading',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page_front.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'revisions',
        6 => 'categories',
        7 => 'tags',
        8 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
));

endif;
