<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_63fb926351a2c',
    'title' => 'Jobs page',
    'fields' => array(
        array(
            'key' => 'field_63fb93c34a900',
            'label' => 'Hero',
            'name' => 'hero',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'wpml_cf_preferences' => 1,
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_63fb94304a901',
                    'label' => 'Heading',
                    'name' => 'heading',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'wpml_cf_preferences' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_63fb94424a902',
                    'label' => 'Lead text',
                    'name' => 'lead_text',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'wpml_cf_preferences' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_63fb944b4a903',
                    'label' => 'Text',
                    'name' => 'text',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'wpml_cf_preferences' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 1,
                ),
                array(
                    'key' => 'field_63fb94794a904',
                    'label' => 'Image',
                    'name' => 'image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'wpml_cf_preferences' => 0,
                    'return_format' => 'array',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'thumbnail',
                ),
            ),
        ),
        array(
            'key' => 'field_63fba14c3d45e',
            'label' => 'Job openings',
            'name' => 'job_openings',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'wpml_cf_preferences' => 1,
            'collapsed' => 'field_63fba1663d45f',
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => 'Add Opening',
            'sub_fields' => array(
                array(
                    'key' => 'field_63fba1663d45f',
                    'label' => 'Title',
                    'name' => 'title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'wpml_cf_preferences' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'parent_repeater' => 'field_63fba14c3d45e',
                ),
                array(
                    'key' => 'field_63fba1823d460',
                    'label' => 'Open link text',
                    'name' => 'open_link_text',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'wpml_cf_preferences' => 0,
                    'default_value' => 'Loe lähemalt',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'parent_repeater' => 'field_63fba14c3d45e',
                ),
                array(
                    'key' => 'field_63fba1a23d461',
                    'label' => 'Close link text',
                    'name' => 'close_link_text',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'wpml_cf_preferences' => 0,
                    'default_value' => 'Sulge',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'parent_repeater' => 'field_63fba14c3d45e',
                ),
                array(
                    'key' => 'field_63fba1b63d462',
                    'label' => 'CTA button text',
                    'name' => 'cta_button_text',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'wpml_cf_preferences' => 0,
                    'default_value' => 'Kandideeri',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'parent_repeater' => 'field_63fba14c3d45e',
                ),
                array(
                    'key' => 'field_63fba1d23d463',
                    'label' => 'CTA button URL',
                    'name' => 'cta_button_url',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'wpml_cf_preferences' => 0,
                    'parent_repeater' => 'field_63fba14c3d45e',
                ),
                array(
                    'key' => 'field_63fba352033fb',
                    'label' => 'Image',
                    'name' => 'image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'wpml_cf_preferences' => 0,
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'parent_repeater' => 'field_63fba14c3d45e',
                ),
                array(
                    'key' => 'field_63fba1e63d464',
                    'label' => 'Text',
                    'name' => 'text',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'wpml_cf_preferences' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'delay' => 0,
                    'parent_repeater' => 'field_63fba14c3d45e',
                ),
            ),
            'rows_per_page' => 20,
        ),
        array(
            'key' => 'field_63fb9a705ac09',
            'label' => 'Sections',
            'name' => 'sections',
            'aria-label' => '',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'wpml_cf_preferences' => 1,
            'layouts' => array(
                'layout_63fb9e3ea40eb' => array(
                    'key' => 'layout_63fb9e3ea40eb',
                    'name' => 'media_block',
                    'label' => 'Media block',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_63fb9ecb5ac0b',
                            'label' => 'Heading',
                            'name' => 'heading',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_63fba4d19354e',
                            'label' => 'Lead text',
                            'name' => 'lead_text',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_63fb9ee35ac0c',
                            'label' => 'Text',
                            'name' => 'text',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                            'delay' => 1,
                            'wpml_cf_preferences' => 0,
                        ),
                        array(
                            'key' => 'field_63fb9f025ac0d',
                            'label' => 'Image',
                            'name' => 'image',
                            'aria-label' => '',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'wpml_cf_preferences' => 0,
                        ),
                        array(
                            'key' => 'field_63fb9f1a5ac0e',
                            'label' => 'Image alignment',
                            'name' => 'image_alignment',
                            'aria-label' => '',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_63fb9f025ac0d',
                                        'operator' => '!=empty',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'choices' => array(
                                'Right' => 'Right',
                                'Left' => 'Left',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'default_value' => 'Left',
                            'layout' => 'vertical',
                            'return_format' => 'value',
                            'save_other_choice' => 0,
                        ),
                        array(
                            'key' => 'field_6410b0ce35f61',
                            'label' => 'Image icon',
                            'name' => 'image_icon',
                            'aria-label' => '',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_63fb9f025ac0d',
                                        'operator' => '!=empty',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 1,
                            'return_format' => 'url',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'svg',
                            'preview_size' => 'thumbnail',
                        ),
                        array(
                            'key' => 'field_6410b10935f62',
                            'label' => 'Image link URL',
                            'name' => 'image_link_url',
                            'aria-label' => '',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_63fb9f025ac0d',
                                        'operator' => '!=empty',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 1,
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_63fba03f8451d',
                            'label' => 'Background color',
                            'name' => 'background_color',
                            'aria-label' => '',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'None' => 'None',
                                'Blue' => 'Blue',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'default_value' => 'None',
                            'layout' => 'vertical',
                            'return_format' => 'value',
                            'wpml_cf_preferences' => 0,
                            'save_other_choice' => 0,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_63fba0e42fd05' => array(
                    'key' => 'layout_63fba0e42fd05',
                    'name' => 'lead',
                    'label' => 'Lead',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_63fba0ef2fd06',
                            'label' => 'Text',
                            'name' => 'text',
                            'aria-label' => '',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 4,
                            'new_lines' => '',
                            'wpml_cf_preferences' => 0,
                        ),
                        array(
                            'key' => 'field_63fbad36010e0',
                            'label' => 'Background color',
                            'name' => 'background_color',
                            'aria-label' => '',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'None' => 'None',
                                'Blue' => 'Blue',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'default_value' => 'None',
                            'layout' => 'vertical',
                            'return_format' => 'value',
                            'wpml_cf_preferences' => 0,
                            'save_other_choice' => 0,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_63fba7d3e3893' => array(
                    'key' => 'layout_63fba7d3e3893',
                    'name' => 'bullet_points',
                    'label' => 'Bullet points',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_63fba844e3896',
                            'label' => 'Heading',
                            'name' => 'heading',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_63fba817e3894',
                            'label' => 'Bullet points',
                            'name' => 'bullet_points',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 1,
                            'collapsed' => 'field_63fba829e3895',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => 'Add Bullet Point',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_63fba829e3895',
                                    'label' => 'Text',
                                    'name' => 'text',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'wpml_cf_preferences' => 0,
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'parent_repeater' => 'field_63fba817e3894',
                                ),
                            ),
                            'rows_per_page' => 20,
                        ),
                        array(
                            'key' => 'field_63fbad0e010df',
                            'label' => 'Background color',
                            'name' => 'background_color',
                            'aria-label' => '',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'None' => 'None',
                                'Blue' => 'Blue',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'default_value' => 'None',
                            'layout' => 'vertical',
                            'return_format' => 'value',
                            'wpml_cf_preferences' => 0,
                            'save_other_choice' => 0,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_63fba11f2403e' => array(
                    'key' => 'layout_63fba11f2403e',
                    'name' => 'job_openings',
                    'label' => 'Job openings',
                    'display' => 'row',
                    'sub_fields' => array(
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
            'button_label' => 'Add Section',
            'min' => '',
            'max' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page_jobs.php',
            ),
        ),
    ),
    'menu_order' => 1,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'discussion',
        3 => 'comments',
        4 => 'format',
        5 => 'page_attributes',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'wpml_field_group_language' => 'et',
));

endif;
